s= set()
s.add(18)
s.add("18")
print(s)
s=set()
s.add(20)
s.add(20.0)
s.add('20')
print(len(s)) #its gives us 2 coz 20.0==20 and its set thats why its not repeating same value
s={}
print(type(s))
f={}
name= input("enter friends name:")
lang= input("enter language:")
f.update({name: lang})
name= input("enter friends name:")
lang= input("enter language:")
f.update({name: lang})
name= input("enter friends name:")
lang= input("enter language:")
f.update({name: lang})
name= input("enter friends name:")
lang= input("enter language:")
f.update({name: lang})
print(f)
